ListenHost = "0.0.0.0"
ListenPort = "8003"

LoginScriptPathFragment = "/wifidog/login"
PortalScriptPathFragment = "/wifidog/portal"
MsgScriptPathFragment = "/wifidog/message"
PingScriptPathFragment = "/wifidog/ping"
AuthScriptPathFragment = "/wifidog/auth"