Host = "0.0.0.0"
Port = "8003"

Path = "/wifidog/"

LoginScriptPathFragment = "login/?"
PortalScriptPathFragment = "portal/?"
MsgScriptPathFragment = "gw_message.php?"
PingScriptPathFragment = "ping/?"
AuthScriptPathFragment = "auth/?"